version: '3.8'

services:
  app:
    build: .
    container_name: servisku-backend
    ports:
      - "8080:80"
    environment:
      - APP_NAME=ServisKu
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://laravel.rajaprasetya.web.id
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-server
      - DB_PORT=3306
      - DB_DATABASE=servisku
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - laravel_logs:/var/www/html/storage/logs
      - ./public/uploads:/var/www/html/public/uploads
    restart: unless-stopped
    networks:
      - vps-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  laravel_logs:
    driver: local

networks:
  vps-network:
    external: true
